In [1]:
import numpy as np


In [4]:
arr1= np.array([[1,3,4]])

In [5]:
arr1.shape

(1, 3)

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.ndim

2

In [11]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr2 *2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
arr2.mean()

5.0

In [16]:
arr2.sum()

45

In [17]:
arr2.std()

2.581988897471611

In [18]:
arr2 > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [19]:
arr3 = np.arange(1,15)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr3.ndim

1

In [21]:
arr3.shape

(14,)

In [23]:
arr3.std()

4.031128874149275

In [25]:
arr4_sqrt = np.sqrt(arr3.std())
arr4_sqrt

2.0077671364352176