In [1]:
import numpy as np


In [4]:
arr1= np.array([[1,3,4]])

In [5]:
arr1.shape

(1, 3)

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.ndim

2

In [11]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr2 *2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
arr2.mean()

5.0

In [16]:
arr2.sum()

45

In [17]:
arr2.std()

2.581988897471611

In [18]:
arr2 > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [19]:
arr3 = np.arange(1,15)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr3.ndim

1

In [21]:
arr3.shape

(14,)

In [23]:
arr3.std()

4.031128874149275

In [27]:
arr3_sqrt = np.sqrt(arr3.std())
arr3_sqrt

2.0077671364352176

In [28]:
arr3[(arr3 > 6)]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
matrix1 = np.array([(1,2),(3,4),(5,6),(7,8),(9,10),(11,12)])
matrix2 = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
matrix1


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [35]:
matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
matrix1[(matrix1 > 5)]

array([ 6,  7,  8,  9, 10, 11, 12])

In [41]:
matrix2[(matrix2>5)]

array([ 6,  7,  8,  9, 10, 11, 12])

In [42]:
matrix1[:,1]

array([ 2,  4,  6,  8, 10, 12])

In [44]:
matrix1[1,1]

4

In [45]:
matrix2[0,:]

array([1, 2, 3, 4])

In [47]:
matrix2[2,3]

12

In [51]:
np.insert(matrix1, 2 , (5,4) , axis = 0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])